#!/usr/bin/expect --

set timeout -1
proc slurp {file} {
    set fh [open $file r]
    set ret [read $fh]
    close $fh
    return $ret
}

set imageName [lindex $argv 0]

if {[string trimleft $imageName] eq ""} {
  puts "No Image file provided"
  exit
}

set cwd [file normalize [file dirname $argv0]]
set imagePath [file join $cwd $imageName]
puts $imageName
puts $imagePath\n

spawn docker run --name dockerpi -it --rm -v $imagePath:/sdcard/filesystem.img lukechilds/dockerpi:vm pi3

expect "raspberrypi login: "
#FIXME: This is a hack to make sure the system is in a ready state to accept the user credentials.
sleep 7
send $env(USERNAME)
send "\n"
expect "Password: "
send $env(PASSWORD)
send "\n"

#############################
# TEMPORARY HOSTNAME CHANGE #
#############################
expect ":~$ "
send "sudo hostname "
send $env(HOSTNAME)
send "\n"

send "exit\n"
expect "$env(HOSTNAME) login: "

send $env(USERNAME)
send "\n"
expect "Password: "
send $env(PASSWORD)
send "\n"

##############################
# UPDATE PACKAGES REPOSITORY #
##############################
expect ":~$ "
send "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg\n"

expect ":~$ "
send "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list\n"

expect ":~$ "
send "sudo sed -i 's/http:\/\/archive.raspberrypi.org\/debian/http:\/\/mirrordirector.raspbian.org\/raspbian\//' /etc/apt/sources.list.d/raspi.list\n"

expect ":~$ "
send "sudo apt-get update\n"

####################
# INSTALL PACKAGES #
####################

expect ":~$ "
# send "sudo apt-get -y upgrade\n"

# expect ":~$ "
send "sudo apt-get -y install dnsmasq network-manager bridge-utils debian-keyring debian-archive-keyring apt-transport-https caddy realvnc-vnc-server || exit\n"


expect {
  ":~$ " { } # Do nothing
  "E:" {
    send_user "[\033[0;31mFAILURE\033[0m] Failed to a package.\n"
    exec docker stop dockerpi
    exit 1
  }
  "login:" {
    send_user "[\033[0;31mFAILURE\033[0m] Failed to install the packages.\n"
    exec docker stop dockerpi
    exit 1
  }
}

send "sudo apt-get install --no-install-recommends -y tigervnc-standalone-server xfonts-scalable xfonts-100dpi xfonts-75dpi novnc || exit\n"

expect {
  ":~$ " { }
  "E:" {
    send_user "[\033[0;31mFAILURE\033[0m] Failed to a package.\n"
    exec docker stop dockerpi
    exit 1
  }
  "login:" {
    send_user "[\033[0;31mFAILURE\033[0m] Failed to install the packages.\n"
    exec docker stop dockerpi
    exit 1
  }
}

send "sudo apt-get clean\n"

###########################
# ACTIVATE NETWORKMANAGER #
###########################
expect ":~$ "
send "sudo systemctl enable --now NetworkManager\n"


#################
# INSTALL CODER #
#################

# install coder
expect ":~$ "
send "sudo curl -fsSL https://raw.githubusercontent.com/coder/code-server/main/install.sh | sh\n"

expect ":~$ "
send "sudo systemctl enable code-server@1000\n"

expect ":~$ "
send "sudo sed -i '/^\\\[Service\\\]/a AmbientCapabilities=CAP_NET_BIND_SERVICE' /lib/systemd/system/code-server@.service\n"


# configure coder
send "sudo mkdir -p ~/.config/code-server\n"

expect ":~$ "
set file [slurp "userhome/.config/code-server/config.yaml"]

expect ":~$ "
send "sudo bash -c 'cat > /home/"
send $env(USERNAME)
send "/.config/code-server/config.yaml' << EOF\n"
send "$file\n"
send "EOF\n"

###################
# CONFIGURE NoVNC #
###################
set file [slurp "lib/systemd/system/novnc.service"]

expect ":~$ "
send "sudo bash -c 'cat > /lib/systemd/system/novnc.service' << EOF\n"
send "$file\n"
send "EOF\n"

set file [slurp "usr/share/novnc/index.html"]
expect ":~$ "
send "sudo bash -c 'cat > /usr/share/novnc/index.html' << EOF\n"
send "$file\n"
send "EOF\n"

expect ":~$ "
send "sudo rm /usr/share/novnc/vnc_lite.html\n"
expect ":~$ "
send "sudo rm /usr/share/novnc/vnc.html\n"

expect ":~$ "
send "sudo ln -s /usr/share/novnc/index.html /usr/share/novnc/vnc.html\n"

expect ":~$ "
send "sudo systemctl enable novnc.service\n"

###################
# CONFIGURE CADDY #
###################

set file [slurp "etc/caddy/Caddyfile"]
expect ":~$ "
send "sudo bash -c 'cat > /etc/caddy/Caddyfile' << EOF\n"
send "$file\n"
send "EOF\n"

expect ":~$ "
send "sudo systemctl reload caddy\n"

###################
# SWITCH TO ROOT  #
###################
expect ":~$ "
send "sudo su -\n"

########################
# SETUP NETWORK BRIDGE #
########################
expect ":~# "
send "sudo brctl addbr br0\n"

########################
# CONFIGURE DNS SERVER #
########################
set file [slurp "etc/dnsmasq.d/usb0"]
expect ":~# "
send "cat << 'EOF' > /etc/dnsmasq.d/usb0\n"
send "$file\n"
send "EOF\n"

set file [slurp "etc/network/interfaces.d/usb0"]
expect ":~# "
send "cat << 'EOF' > /etc/network/interfaces.d/usb0\n"
send "$file\n"
send "EOF\n"


########################
# CONFIGURE USB GADGET #
########################
set file [slurp "usr/local/sbin/multigadget"]
expect ":~# "
send "cat << 'EOF' > /usr/local/sbin/multigadget\n"
send "$file\n"
send "EOF\n"
expect ":~# "
send "chmod +x /usr/local/sbin/multigadget\n"

set file [slurp "lib/systemd/system/multigadget.service"]
expect ":~# "
send "cat << 'EOF' > /lib/systemd/system/multigadget.service\n"
send "$file\n"
send "EOF\n"
expect ":~# "
send "systemctl enable multigadget.service\n"


####################
# CONFIGURE KERNEL #
####################
expect ":~# "
send "echo dtoverlay=dwc2 >> /boot/config.txt\n"

expect ":~# "
send "touch /boot/ssh\n"

expect ":~# "
send "echo dwc2 >> /etc/modules\n"
send "echo libcomposite >> /etc/modules\n"



##################
# CONFIGURE DHCP #
##################
expect ":~# "
send "echo denyinterfaces usb0 br0 >> /etc/dhcpcd.conf\n"

##########################
# ENABLE NETWORK MANAGER #
##########################
expect ":~# "
send "raspi-config nonint do_netconf 2\n"

################
# SET HOSTNAME #
################
expect ":~# "
send "raspi-config nonint do_hostname "
send $env(HOSTNAME)
send "\n"

###################
# CONFIGURE AVAHI #
###################
expect ":~# "
send "sed -i 's/#allow-interfaces=eth0/allow-interfaces=br0/' /etc/avahi/avahi-daemon.conf\n"

##############
# ENABLE SSH #
##############
expect ":~# "
send "raspi-config nonint do_ssh 0\n"
expect ":~# "

############################
# CONFIGURE RealVNC Server #
############################
expect ":~# "
send "raspi-config nonint do_vnc 0\n"

#############################
# CONFIGURE TigerVNC Server #
#############################
expect ":~# "
send "sed -i \"s/\\\[XDMCPServer\\\]/\\\[XDMCPServer\\\]\\nenabled=true\\nport=177/\" /etc/lightdm/lightdm.conf\n"

set file [slurp "lib/systemd/system/tigervnc@.service"]

expect ":~# "
send "cat << 'EOF' > /lib/systemd/system/tigervnc@.service\n"
send "$file\n"
send "EOF\n"

set file [slurp "lib/systemd/system/tigervnc.socket"]

expect ":~# "
send "cat << 'EOF' > /lib/systemd/system/tigervnc.socket\n"
send "$file\n"
send "EOF\n"

expect ":~# "
send "systemctl enable tigervnc.socket\n"


##########
# FINISH #
##########
send "poweroff\n"

expect "reboot: Power down"
exec docker stop dockerpi
exit
