#!/bin/bash

#############
# VARIABLES #
#############
# USB Device Information
USB_VERSION="0x0200" # USB2

DEVICE_CLASS="0x02" # Networking Device Class
DEVICE_CLASS_RESET="0xEF" # Composite Device Class
DEVICE_SUBCLASS="0x00" # Common Sub Class
DEVICE_SUBCLASS_RESET="0x02" # Composite Device Sub Class
DEVICE_PROTOCOL="0x01" # Interface Association Descriptor

VENDOR_ID="0x1d6b"  # Linux Foundation
PRODUCT_ID="0x0104" # Multifunction Composite Gadget

MANUFACTURER="VaneixusPrime"
PRODUCT="RaspberryPi Multi-Gadget Device"
VERSION=0x0106
SERIAL="fedcba9876543210"

MAX_POWER="250" # 250 mA

LANGUAGE="0x409" # English

# USB Device Functions
CONFIG_1="RNDIS"

ENABLE_SERIAL=true
ENABLE_NETWORKING=true
ENABLE_MTP=true

# ECM Network Information
HOST="48:6f:73:74:50:43" # "HostPC"
SELF_NDIS="42:61:64:55:53:43"

# Microsoft OS Descriptors
MS_VENDOR_CODE="0xcd" # Microsoft
MS_QW_SIGN="MSFT100" # "MSFT100"
MS_COMPATIBLE_ID="RNDIS" # matches Windows RNDIS Drivers
MS_SUB_COMPATIBLE_ID="5162001" # matches Windows RNDIS 6.0 Driver


cd /sys/kernel/config/usb_gadget/ || exit 1
mkdir -p multigadget
cd multigadget || exit 1

# USB DEVICE CONFIGURATION
###########################
echo $VENDOR_ID   > idVendor
echo $PRODUCT_ID  > idProduct

# USB CONNECTION CONFIGURATION
###############################
echo $VERSION         > bcdDevice
echo $USB_VERSION     > bcdUSB
echo $DEVICE_CLASS    > bDeviceClass
echo $DEVICE_SUBCLASS > bDeviceSubClass
echo $DEVICE_PROTOCOL > bDeviceProtocol
echo 0x40 > bMaxPacketSize0

mkdir -p strings/$LANGUAGE
echo "$SERIAL"        > strings/$LANGUAGE/serialnumber
echo "$MANUFACTURER"  > strings/$LANGUAGE/manufacturer
echo "$PRODUCT"       > strings/$LANGUAGE/product


# CONFIG 1
###########
mkdir -p configs/c.1/strings/$LANGUAGE
echo $CONFIG_1  > configs/c.1/strings/$LANGUAGE/configuration
echo $MAX_POWER > configs/c.1/MaxPower

ln -s configs/c.1 os_desc


# Microsoft OS Descriptors
###########################
echo "1" > os_desc/use
echo $MS_VENDOR_CODE > os_desc/b_vendor_code
echo $MS_QW_SIGN     > os_desc/qw_sign


###################
# Start functions #
###################

# Ethernet
###########
if [ "$ENABLE_NETWORKING" = true ]; then
  echo 'Enabling USB Ethernet...' | systemd-cat
  mkdir -p functions/rndis.usb0

  echo $HOST                  > functions/rndis.usb0/host_addr
  echo $SELF_NDIS             > functions/rndis.usb0/dev_addr
  echo $MS_COMPATIBLE_ID      > functions/rndis.usb0/os_desc/interface.rndis/compatible_id
  echo $MS_SUB_COMPATIBLE_ID  > functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id

  ln -s functions/rndis.usb0 configs/c.1/

  # Allow Windows to install RNDIS drivers automatically.
  echo 'Starting configuration early to allow Windows to detect and install drivers for the USB Ethernet Interface.'
  ls /sys/class/udc > UDC
  sleep 5
  echo "" > UDC
  echo 'Enabled USB Ethernet.' | systemd-cat
fi

# Force Windows to re-read the descriptors.
echo $DEVICE_CLASS_RESET > bDeviceClass
echo $DEVICE_SUBCLASS_RESET > bDeviceSubClass

# Serial
#########
if [ "$ENABLE_SERIAL" = true ]; then
  echo 'Enabling USB Serial...' | systemd-cat
  mkdir -p functions/acm.usb0

  ln -s functions/acm.usb0 configs/c.1/

  sudo systemctl enable getty@ttyGS0.service
  echo 'Enabled USB Serial.' | systemd-cat
fi

if [ "$ENABLE_MTP" = true ]; then
  echo 'Enabling MTP...' | systemd-cat
  cat /etc/umtprd/umtprd.conf-template > /etc/umtprd/umtprd.conf

  home_folders=(/home/*)
  for home in "${home_folders[@]}"; do
    echo 'storage "'"$home"'" "'"${home##*/}"'" "rw"' >> /etc/umtprd/umtprd.conf
  done

  mkdir functions/ffs.mtp

  ln -s functions/ffs.mtp configs/c.1/

  mkdir -p /dev/ffs-mtp
  mount -t functionfs mtp /dev/ffs-mtp

  umtprd &
  echo 'Enabled USB MTP.' | systemd-cat
fi

#################
# End functions #
#################
# Power on the gadget.
echo 'Enabling USB Gadget...' | systemd-cat
ls /sys/class/udc > UDC
echo 'Enabled USB Gadget.' | systemd-cat